// This file is no longer used.
// The generic instrumentor is now in Program.cs and reads namespace allowlists
// from namespaces.json (generated by fuzz-prep-multi.py) or CLI arguments.
//
// See Program.cs for usage.
