// AUTO-GENERATED by fuzz-prep.py
// Project: SampleWebApiAspNetCore
// Detected namespaces: SampleWebApiAspNetCore.Controllers.v1, SampleWebApiAspNetCore.Services

Console.WriteLine("Instrumenting SampleWebApiAspNetCore business logic...");
var dllPath = args.Length > 0 ? args[0] : "/app/bin/Release/net8.0/SampleWebApiAspNetCore.dll";

bool ShouldInstrument(string fullName)
{
    // Exclude common known problematic classes for startup/migrations
    if (fullName.Contains("Program") || 
        fullName.Contains("Startup") || 
        fullName.Contains("Extensions") ||
        fullName.Contains("Migrations") ||
        fullName.Contains("Seed") ||
        fullName.Contains("RolesManager"))
    {
        return false;
    }

    // Auto-detected filter pattern
    Console.WriteLine($"Checking: {fullName}");
    if ((fullName.Contains("SampleWebApiAspNetCore.Controllers.v1") || fullName.Contains("SampleWebApiAspNetCore.Services")))
    {
        Console.WriteLine($"  ✓ Instrumenting: {fullName}");
        return true;
    }
    return false;
}

try
{
    SharpFuzz.Fuzzer.Instrument(dllPath, ShouldInstrument, SharpFuzz.Options.Value);
    Console.WriteLine("✅ Instrumentation complete!");
}
catch (Exception ex)
{
    Console.WriteLine($"❌ Error: {ex.ToString()}");
    throw;
}
