package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// poc.go — Proof-of-concept artifact generation: PoC shell scripts,
// exploit timeline Markdown files, curl command builder, and header resolution.

func (f *Fuzzer) resolvedCrashHeaders(item WorkItem) map[string]string {
	headers := cloneStringMap(item.Headers)
	idHeaders, idToken := f.identityAuth(item.Identity)
	for k, v := range idHeaders {
		if strings.TrimSpace(headers[k]) == "" {
			headers[k] = v
		}
	}
	if idToken != "" {
		headers["Authorization"] = "Bearer " + idToken
	} else {
		f.authMu.RLock()
		tok := strings.TrimSpace(f.token)
		f.authMu.RUnlock()
		if tok != "" {
			headers["Authorization"] = "Bearer " + tok
		}
	}
	if strings.TrimSpace(getHeaderCI(headers, "Content-Type")) == "" && strings.TrimSpace(item.Body) != "" {
		setHeaderCI(headers, "Content-Type", "application/json")
	}
	return headers
}

func crashHeaderKeys(headers map[string]string) []string {
	keys := make([]string, 0, len(headers))
	for k := range headers {
		if strings.EqualFold(k, "Host") || strings.EqualFold(k, "Content-Length") || strings.EqualFold(k, "Transfer-Encoding") {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func (f *Fuzzer) buildInlineCurlCommand(item WorkItem, headers map[string]string) string {
	path := item.Path
	if strings.TrimSpace(path) == "" {
		path = "/"
	}
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}
	method := strings.ToUpper(strings.TrimSpace(item.Method))
	if method == "" {
		method = "GET"
	}

	parts := []string{
		"TARGET_HOST=\"${TARGET_HOST:-" + escapeForDoubleQuotedBash(strings.TrimRight(f.target, "/")) + "}\";",
		"curl -i -sS -X \"" + escapeForDoubleQuotedBash(method) + "\"",
		"\"$TARGET_HOST" + escapeForDoubleQuotedBash(path) + "\"",
	}
	for _, hk := range crashHeaderKeys(headers) {
		parts = append(parts, "-H \""+escapeForDoubleQuotedBash(hk+": "+headers[hk])+"\"")
	}
	if strings.TrimSpace(item.Body) != "" {
		parts = append(parts, "--data-raw \""+escapeForDoubleQuotedBash(item.Body)+"\"")
	} else {
		parts = append(parts, "--data ''")
	}
	return strings.Join(parts, " ")
}

func (f *Fuzzer) writeCrashPoC(sig string, res SendResult, pocItem WorkItem, triage, repro, minimized map[string]any) string {
	if strings.TrimSpace(f.cfg.PocDir) == "" {
		return ""
	}
	if err := os.MkdirAll(f.cfg.PocDir, 0o755); err != nil {
		return ""
	}
	path := filepath.Join(f.cfg.PocDir, "poc-"+sig+".sh")
	headers := f.resolvedCrashHeaders(pocItem)
	headerKeys := crashHeaderKeys(headers)

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\nset -euo pipefail\n\n")
	b.WriteString("# Auto-generated by Void\n")
	b.WriteString("# signature: " + sig + "\n")
	b.WriteString("# method: " + pocItem.Method + "\n")
	b.WriteString("# path: " + normalizePath(pocItem.Path) + "\n")
	if cls := toString(triage["classification"]); cls != "" {
		b.WriteString("# triage: " + cls + " severity=" + toString(triage["severity_score"]) + " dev_mode=" + toString(triage["dev_mode"]) + "\n")
	}
	if layer := toString(triage["crash_layer"]); layer != "" && layer != "unknown" {
		b.WriteString("# crash_layer: " + layer + "\n")
	}
	if st := toString(repro["stability_pct"]); st != "" {
		b.WriteString("# repro stability: " + st + "%\n")
	}
	if len(pocItem.Trace) > 1 {
		b.WriteString("# sequence trace:\n")
		for i, step := range pocItem.Trace {
			b.WriteString(fmt.Sprintf("#   %d) %s %s\n", i+1, step.Method, step.Path))
		}
	}
	b.WriteString("\nTARGET_HOST=\"${TARGET_HOST:-" + shellQuoteDouble(f.target) + "}\"\n\n")
	b.WriteString("curl -i -sS -X " + shellQuoteDouble(strings.ToUpper(pocItem.Method)) + " \"$TARGET_HOST" + escapeForDoubleQuotedBash(pocItem.Path) + "\" \\\n")
	for _, hk := range headerKeys {
		b.WriteString("  -H \"" + escapeForDoubleQuotedBash(hk+": "+headers[hk]) + "\" \\\n")
	}
	if strings.TrimSpace(pocItem.Body) != "" {
		b.WriteString("  --data-raw \"" + escapeForDoubleQuotedBash(pocItem.Body) + "\"\n")
	} else {
		b.WriteString("  --data ''\n")
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o755); err != nil {
		return ""
	}
	f.pocCount++
	return path
}

func (f *Fuzzer) writeExploitTimeline(sig string, res SendResult, pocItem WorkItem) string {
	if strings.TrimSpace(f.cfg.TimelineDir) == "" {
		return ""
	}
	if err := os.MkdirAll(f.cfg.TimelineDir, 0o755); err != nil {
		return ""
	}
	path := filepath.Join(f.cfg.TimelineDir, "timeline-"+sig+".md")
	trace := pocItem.Trace
	if len(trace) == 0 {
		trace = []TraceStep{{Method: pocItem.Method, Path: normalizePath(pocItem.Path), Mutation: pocItem.MutationName}}
	}
	if len(trace) > traceDepthMax {
		trace = trace[len(trace)-traceDepthMax:]
	}

	var b strings.Builder
	b.WriteString("# Exploit Timeline " + sig + "\n\n")
	b.WriteString("```mermaid\nsequenceDiagram\n")
	b.WriteString("    participant F as Fuzzer\n")
	b.WriteString("    participant API as API\n")
	for i, st := range trace {
		msg := fmt.Sprintf("%d. %s %s", i+1, strings.ToUpper(st.Method), sanitizeText(normalizePath(st.Path), 80))
		b.WriteString("    F->>API: " + mermaidEscape(msg) + "\n")
		if i == len(trace)-1 {
			b.WriteString(fmt.Sprintf("    API-->>F: %d crash\n", res.Status))
		} else {
			b.WriteString("    API-->>F: success/transition\n")
		}
	}
	b.WriteString("```\n")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return ""
	}
	return path
}
