"""Legacy `--inject-mode source` support: generates CoverageExtensions.cs (the
in-source SHM coverage middleware), patches the target's own .csproj files
and Program.cs/Startup.cs to reference and wire it up, and writes the
coverage smoke-test script. Retained for targets where source editing is
preferred, or where the middleware needs to sit inside the app's own
exception handler for maximal production-mode exception-type fidelity --
the default zero-edit hook mode (instrumentor_gen.py) never touches the
target's source at all.
"""

import re
import json
from pathlib import Path

from .models import MultiAnalysisResult
from .detect import _detect_builder_name, _detect_app_name


def patch_all_csprojs(output_path: Path):
    """Apply AllowUnsafeBlocks and SharpFuzz reference to main project csprojs.

    Skips test projects and instrumentor projects.
    Handles Central Package Management (Directory.Packages.props) if present.
    """
    cpvm_file = output_path / "Directory.Packages.props"
    has_cpvm = cpvm_file.exists()
    sharpfuzz_version = "2.1.1"

    if has_cpvm:
        print(f"  Detected Central Package Management: {cpvm_file.name}")
        content = cpvm_file.read_text()
        if 'Include="SharpFuzz"' not in content:
            if '</ItemGroup>' in content:
                content = content.replace(
                    '</ItemGroup>',
                    f'  <PackageVersion Include="SharpFuzz" Version="{sharpfuzz_version}" />\n  </ItemGroup>',
                    1
                )
            else:
                content = content.replace(
                    '</Project>',
                    f'  <ItemGroup>\n    <PackageVersion Include="SharpFuzz" Version="{sharpfuzz_version}" />\n  </ItemGroup>\n</Project>'
                )
            cpvm_file.write_text(content)
            print("  Added SharpFuzz version to Directory.Packages.props")

    for csproj in output_path.rglob('*.csproj'):
        csproj_str = str(csproj).lower()
        if 'instrumentor' in csproj_str:
            continue
        if 'test' in csproj.name.lower() or '/test/' in csproj_str or '\\test\\' in csproj_str:
            print(f"  Skipped test project: {csproj.name}")
            continue

        content = csproj.read_text()

        if '<AllowUnsafeBlocks>true</AllowUnsafeBlocks>' not in content:
            content = content.replace(
                '<PropertyGroup>',
                '<PropertyGroup>\n    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>',
                1
            )

        if 'Include="SharpFuzz"' not in content:
            ref_line = (
                '<PackageReference Include="SharpFuzz" />'
                if has_cpvm
                else f'<PackageReference Include="SharpFuzz" Version="{sharpfuzz_version}" />'
            )

            if '</ItemGroup>' in content:
                content = content.replace('</ItemGroup>', f'  {ref_line}\n  </ItemGroup>', 1)
            else:
                content = content.replace(
                    '</Project>',
                    f'  <ItemGroup>\n    {ref_line}\n  </ItemGroup>\n</Project>'
                )

        csproj.write_text(content)
        print(f"  Patched {csproj.name}")


# ============================================================================
# CoverageExtensions.cs generation
# ============================================================================

def generate_multi_coverage_helper(result: MultiAnalysisResult, output_path: Path):
    """Generate CoverageExtensions.cs in the main project"""
    main_proj = next((p for p in result.projects if p.name == result.main_project), result.projects[0])

    # Use RootNamespace if detected, otherwise fall back to project name
    ns_prefix = main_proj.root_namespace or result.main_project

    # Determine target subdirectory: prefer Utilities/ (standard ASP.NET convention), fall back to Helpers/
    utilities_dir = output_path / main_proj.path / "Utilities"
    helpers_dir = output_path / main_proj.path / "Helpers"
    subdir_name = "Utilities" if utilities_dir.exists() else "Helpers"

    code = f"""// AUTO-GENERATED by fuzz-prep-multi.py
#nullable disable
#pragma warning disable
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.IO.MemoryMappedFiles;
using System.Linq;
using System.Runtime.InteropServices;
using System.Reflection;
using System.Text.Json;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace {ns_prefix}.{subdir_name}
{{
    public class CoverageSnapshot
    {{
        public string TraceId {{ get; set; }}
        public string Endpoint {{ get; set; }}
        public int CoverageBefore {{ get; set; }}
        public int CoverageAfter {{ get; set; }}
        public int CoverageDelta {{ get; set; }}
        public DateTime Timestamp {{ get; set; }}
    }}

    public static class CoverageExtensions
    {{
        private const string SHM_PATH = "/coverage_shm/bitmap";
        private const int DEFAULT_SHM_SIZE = 262144;
        private const int MIN_SHM_SIZE = 65536;
        private const int MAX_SHM_SIZE = 8 * 1024 * 1024;
        // Top-20 #17: real instrumented-type count captured at build time by
        // instrumentor/Program.cs, used both to auto-size SHM_SIZE below (when the
        // env var isn't explicitly set) and reported via /shm/health for transparency.
        private static readonly int InstrumentedTypeCount = ResolveInstrumentedTypeCount();
        private static readonly int SHM_SIZE = ResolveShmSize();
        // Top-20+ #22: string/int literals harvested from the target's own IL at
        // instrument time by instrumentor/Program.cs::ConstantExtractor, read once
        // (static -- extracted at build time, never changes during a run) and served
        // over GET /shm/constants for the Go engine to fold into its mutation pool.
        private static readonly (string[] Strings, string[] Ints) ExtractedConstants = ResolveConstants();

        private static IntPtr globalShmAddr = IntPtr.Zero;
        private static bool isSynced = false;
        private static bool isFileBacked = false;
        private static MemoryMappedFile mmf;
        private static MemoryMappedViewAccessor accessor;
        private static ConcurrentDictionary<string, CoverageSnapshot> traceCoverage = new ConcurrentDictionary<string, CoverageSnapshot>();

        // ── AFL-style hit-count buckets + bucketed virgin map ──────────────────
        // Each edge's raw 8-bit hit count is classified into a log-scale bucket
        // (1, 2, 3, 4-7, 8-15, 16-31, 32-127, 128+). seenBuckets[i] holds the OR
        // of every bucket bit ever observed for edge i. A bucket bit that is new
        // for an edge is new coverage — so an edge run once is distinguished from
        // the same edge run 50 or 5000 times, letting the fuzzer keep making
        // progress inside loops/pagination/state machines instead of plateauing
        // the instant every edge has been touched at least once.
        private static readonly byte[] CountClass = BuildCountClass();
        private static byte[] seenBuckets;      // bucketed virgin map (size SHM_SIZE)
        private static int totalClasses = 0;    // running count of distinct (edge, bucket) classes discovered
        private static readonly object covLock = new object();

        private static byte[] BuildCountClass()
        {{
            var t = new byte[256];
            for (int i = 0; i < 256; i++)
            {{
                byte c = (byte)i;
                byte v;
                if (c == 0) v = 0;
                else if (c == 1) v = 1;
                else if (c == 2) v = 2;
                else if (c == 3) v = 4;
                else if (c <= 7) v = 8;
                else if (c <= 15) v = 16;
                else if (c <= 31) v = 32;
                else if (c <= 127) v = 64;
                else v = 128;
                t[i] = v;
            }}
            return t;
        }}

        // MergeAndCountNovel folds the live coverage bitmap into the persistent
        // bucketed virgin map and returns how many NEW (edge, bucket) classes the
        // just-completed request discovered. Novelty is measured against the shared
        // virgin map (first-observer-wins): when two concurrent requests both reach
        // new code the credit is claimed once, not smeared across both — which is
        // the concurrency-attribution bug the old global before/after delta had.
        // A single pass (with an all-zero 8-byte word fast path) replaces the two
        // full 256KB bitmap scans the middleware previously did per request.
        private static int MergeAndCountNovel()
        {{
            if (globalShmAddr == IntPtr.Zero || seenBuckets == null) return 0;
            int novel = 0;
            lock (covLock)
            {{
                unsafe
                {{
                    byte* b = (byte*)globalShmAddr;
                    int n = SHM_SIZE;
                    int i = 0;
                    for (; i + 8 <= n; i += 8)
                    {{
                        if (*(ulong*)(b + i) == 0UL) continue;
                        for (int j = 0; j < 8; j++)
                        {{
                            byte c = b[i + j];
                            if (c == 0) continue;
                            byte bucket = CountClass[c];
                            if ((seenBuckets[i + j] & bucket) == 0)
                            {{
                                seenBuckets[i + j] |= bucket;
                                novel++;
                            }}
                        }}
                    }}
                    for (; i < n; i++)
                    {{
                        byte c = b[i];
                        if (c == 0) continue;
                        byte bucket = CountClass[c];
                        if ((seenBuckets[i] & bucket) == 0)
                        {{
                            seenBuckets[i] |= bucket;
                            novel++;
                        }}
                    }}
                }}
                totalClasses += novel;
            }}
            return novel;
        }}

        // ResolveInstrumentedTypeCount reads the JSONL meta file instrumentor/Program.cs
        // appends next to the app's DLLs (one line per instrumented assembly) and sums
        // instrumented_types across them. Returns 0 if the file is absent (e.g. a build
        // predating this feature) -- callers must treat 0 as "unknown", not "zero types".
        private static int ResolveInstrumentedTypeCount()
        {{
            try
            {{
                var metaPath = Path.Combine(AppContext.BaseDirectory, ".upsidefuzz_instrumented.jsonl");
                if (!File.Exists(metaPath)) return 0;
                int total = 0;
                const string key = "\\"instrumented_types\\":";
                foreach (var line in File.ReadAllLines(metaPath))
                {{
                    var idx = line.IndexOf(key, StringComparison.Ordinal);
                    if (idx < 0) continue;
                    int start = idx + key.Length;
                    int end = start;
                    while (end < line.Length && char.IsDigit(line[end])) end++;
                    if (end > start && int.TryParse(line.Substring(start, end - start), out var n))
                        total += n;
                }}
                return total;
            }}
            catch {{ return 0; }}
        }}

        // ResolveConstants reads .upsidefuzz_constants.jsonl (written next to the app's
        // DLLs by instrumentor/Program.cs::ConstantExtractor, one line per instrumented
        // assembly) and unions strings/ints across all lines, capped at the same
        // 512/256 bounds ConstantExtractor itself enforces per assembly. Absent file
        // (build predates this feature) resolves to empty arrays, never an error.
        private static (string[] Strings, string[] Ints) ResolveConstants()
        {{
            const int maxStrings = 512, maxInts = 256;
            var strs = new List<string>();
            var strSeen = new HashSet<string>(StringComparer.Ordinal);
            var ints = new List<string>();
            var intSeen = new HashSet<string>(StringComparer.Ordinal);
            try
            {{
                var metaPath = Path.Combine(AppContext.BaseDirectory, ".upsidefuzz_constants.jsonl");
                if (!File.Exists(metaPath)) return (Array.Empty<string>(), Array.Empty<string>());
                foreach (var line in File.ReadAllLines(metaPath))
                {{
                    if (string.IsNullOrWhiteSpace(line)) continue;
                    try
                    {{
                        using var doc = JsonDocument.Parse(line);
                        var root = doc.RootElement;
                        if (strs.Count < maxStrings && root.TryGetProperty("strings", out var sArr) && sArr.ValueKind == JsonValueKind.Array)
                        {{
                            foreach (var el in sArr.EnumerateArray())
                            {{
                                if (strs.Count >= maxStrings) break;
                                var s = el.GetString();
                                if (!string.IsNullOrEmpty(s) && strSeen.Add(s)) strs.Add(s);
                            }}
                        }}
                        if (ints.Count < maxInts && root.TryGetProperty("ints", out var iArr) && iArr.ValueKind == JsonValueKind.Array)
                        {{
                            foreach (var el in iArr.EnumerateArray())
                            {{
                                if (ints.Count >= maxInts) break;
                                var s = el.GetString();
                                if (!string.IsNullOrEmpty(s) && intSeen.Add(s)) ints.Add(s);
                            }}
                        }}
                    }}
                    catch {{ /* one malformed line must not lose the rest */ }}
                }}
            }}
            catch {{ }}
            return (strs.ToArray(), ints.ToArray());
        }}

        private static int ResolveShmSize()
        {{
            try
            {{
                var raw = Environment.GetEnvironmentVariable("SHM_SIZE");
                if (int.TryParse(raw, out var parsed))
                {{
                    if (parsed < MIN_SHM_SIZE) return MIN_SHM_SIZE;
                    return parsed;
                }}
            }}
            catch {{ }}
            // Top-20 #17: size the bitmap from the real instrumented-type count instead
            // of a fixed 256KB guess, when SHM_SIZE isn't pinned explicitly. SharpFuzz
            // exposes no public branch/edge count, so instrumented TYPE count is used as
            // a proxy -- budget ~512 bitmap bytes per instrumented type, rounded up to a
            // power of two and clamped to [MIN_SHM_SIZE, MAX_SHM_SIZE].
            try
            {{
                if (InstrumentedTypeCount > 0)
                {{
                    long estimate = (long)InstrumentedTypeCount * 512;
                    int size = MIN_SHM_SIZE;
                    while (size < estimate && size < MAX_SHM_SIZE) size <<= 1;
                    return size;
                }}
            }}
            catch {{ }}
            return DEFAULT_SHM_SIZE;
        }}

        public static void Initialize()
        {{
            if (globalShmAddr != IntPtr.Zero) return;

            if (Directory.Exists(Path.GetDirectoryName(SHM_PATH)))
            {{
                try {{
                    var fs = new FileStream(SHM_PATH, FileMode.OpenOrCreate,
                        FileAccess.ReadWrite, FileShare.ReadWrite);
                    fs.SetLength(SHM_SIZE);
                    mmf = MemoryMappedFile.CreateFromFile(fs, null, SHM_SIZE,
                        MemoryMappedFileAccess.ReadWrite, HandleInheritability.None, false);
                    accessor = mmf.CreateViewAccessor(0, SHM_SIZE);
                    unsafe {{
                        byte* ptr = null;
                        accessor.SafeMemoryMappedViewHandle.AcquirePointer(ref ptr);
                        globalShmAddr = (IntPtr)ptr;
                    }}
                    isFileBacked = true;
                }} catch {{
                    globalShmAddr = Marshal.AllocHGlobal(SHM_SIZE);
                }}
            }}
            else
            {{
                globalShmAddr = Marshal.AllocHGlobal(SHM_SIZE);
            }}

            unsafe {{ byte* b = (byte*)globalShmAddr; for (int i = 0; i < SHM_SIZE; i++) b[i] = 0; }}
            seenBuckets = new byte[SHM_SIZE];
            totalClasses = 0;
            SyncSharpFuzz();
        }}

        // SanitizeHeader makes an arbitrary exception string safe as an HTTP header
        // value: strips CR/LF/control chars and truncates. Exception messages routinely
        // contain newlines and non-ASCII, which would throw when assigned to a header.
        private static string SanitizeHeader(string s)
        {{
            if (string.IsNullOrEmpty(s)) return "";
            var sb = new System.Text.StringBuilder(Math.Min(s.Length, 1024));
            foreach (var c in s)
            {{
                if (sb.Length >= 1024) break;
                if (c == '\\r' || c == '\\n' || c == '\\t') {{ sb.Append(' '); continue; }}
                if (c >= 32 && c < 127) sb.Append(c);
            }}
            return sb.ToString();
        }}

        public static IApplicationBuilder UseCoverageMiddleware(this IApplicationBuilder app)
        {{
            Initialize();

            return app.Use(async (context, next) =>
            {{
                if (globalShmAddr != IntPtr.Zero && !isSynced) {{ SyncSharpFuzz(); }}

                // Use X-Fuzz-Request-Id header for per-request coverage attribution.
                // The fuzzer sends this header; we return X-Coverage-Delta in the response.
                var requestId = context.Request.Headers["X-Fuzz-Request-Id"].ToString();
                if (string.IsNullOrEmpty(requestId))
                    requestId = "default-" + Guid.NewGuid().ToString("N").Substring(0, 8);

                string exceptionTypeName = null;
                string exceptionMessage = null;
                bool isFuzzRequest = !string.IsNullOrEmpty(context.Request.Headers["X-Fuzz-Request-Id"]);
                // Per-request novelty is computed ONCE, after the pipeline runs, by
                // merging the live bitmap into the shared bucketed virgin map. This
                // replaces the old global before/after double full-scan (two 256KB
                // passes per request) and its concurrency smearing: the delta is now
                // the count of buckets THIS request was first to discover.
                int coverageDelta = -1;
                try {{
                    await next();
                }} catch (Exception ex) {{
                    exceptionTypeName = ex.GetType().FullName;
                    exceptionMessage = ex.Message;
                    // PRODUCTION-MODE FIX: in non-Development mode the app's exception handler
                    // starts the response (Response.HasStarted = true) and clears headers before
                    // our finally block runs — losing X-Exception-Type on ~all prod 500s. For
                    // FUZZ requests only, short-circuit here and emit our own 500 carrying the
                    // exception type + message. Real traffic (no X-Fuzz-Request-Id) is untouched:
                    // we re-throw so the app's normal error handling still runs for it.
                    if (isFuzzRequest && !context.Response.HasStarted) {{
                        try {{
                            context.Response.Clear();
                            context.Response.StatusCode = 500;
                            coverageDelta = MergeAndCountNovel();
                            context.Response.Headers["X-Coverage-Delta"] = coverageDelta.ToString();
                            context.Response.Headers["X-Coverage-Edges"] = totalClasses.ToString();
                            context.Response.Headers["X-Exception-Type"] = SanitizeHeader(exceptionTypeName);
                            context.Response.Headers["X-Exception-Message"] = SanitizeHeader(exceptionMessage);
                            context.Response.ContentType = "application/json";
                            await context.Response.WriteAsync("{{\\"error\\":\\"unhandled_exception\\"}}");
                        }} catch {{ }}
                        return;
                    }}
                    throw;
                }} finally {{
                    // Single-pass novelty merge (skipped if the short-circuit branch already did it).
                    if (coverageDelta < 0) coverageDelta = MergeAndCountNovel();
                    // Inject per-request coverage into response headers — the fuzzer reads
                    // X-Coverage-Delta directly from the response, no extra round trip.
                    try {{
                        if (!context.Response.HasStarted) {{
                            context.Response.Headers["X-Coverage-Delta"] = coverageDelta.ToString();
                            context.Response.Headers["X-Coverage-Edges"] = totalClasses.ToString();
                            if (exceptionTypeName != null)
                                context.Response.Headers["X-Exception-Type"] = SanitizeHeader(exceptionTypeName);
                            if (exceptionMessage != null)
                                context.Response.Headers["X-Exception-Message"] = SanitizeHeader(exceptionMessage);
                        }}
                    }} catch {{ }}
                    // Bounded cleanup to prevent unbounded memory growth under sustained fuzzing.
                    if (traceCoverage.Count > 5000) {{
                        var oldestKeys = traceCoverage.Keys.Take(1000).ToArray();
                        foreach (var k in oldestKeys) traceCoverage.TryRemove(k, out _);
                    }}
                    traceCoverage[requestId] = new CoverageSnapshot
                    {{
                        TraceId = requestId,
                        Endpoint = context.Request.Path,
                        CoverageBefore = 0,
                        CoverageAfter = totalClasses,
                        CoverageDelta = coverageDelta,
                        Timestamp = DateTime.UtcNow
                    }};
                }}
            }});
        }}

        private static string syncError = "None";
        private static string lastAttempt = "None";

        // Self-verifying, fail-closed instrumentation (Top-20 #4): track which
        // assemblies are "app" code (not framework/SharpFuzz itself) so /shm/health
        // can report whether instrumentation actually reached the target's own
        // code, not just that the SharpFuzz runtime loaded. Mirrors
        // instrumentor/Program.cs's `frameworkPrefixes` — kept in sync manually.
        private static readonly string[] frameworkPrefixes = {{
            "System.", "Microsoft.", "SharpFuzz.", "Mono.", "Internal.",
            "Newtonsoft.", "Swashbuckle.", "NSwag.", "FluentValidation.",
            "Serilog.", "MediatR.", "AutoMapper.", "Dapper.",
            "Npgsql.", "MySqlConnector.", "StackExchange.",
            "Polly.", "Grpc.", "Google.Protobuf.",
        }};
        // linked_app_assemblies is deliberately NOT tracked per-assembly: SharpFuzz's
        // Trace.SharedMem type lives only in SharpFuzz.Common.dll, never in the app's
        // own IL-rewritten assemblies, so "does this app assembly define the Trace
        // type" is always false and would be a false-negative fail-closed signal.
        // The only architecturally honest way to verify instrumentation reached app
        // code is to check whether the shared bitmap actually moves after real
        // traffic — done engine-side (void/go/coverage.go::checkCoverageHealth) via a
        // warm-up probe. This list is purely informational: which app assemblies the
        // runtime has observed loaded, for diagnostics when that probe fails.
        private static readonly ConcurrentDictionary<string, byte> seenAppAssemblies = new ConcurrentDictionary<string, byte>();

        private static bool IsAppAssembly(string name)
        {{
            if (string.IsNullOrEmpty(name)) return false;
            foreach (var prefix in frameworkPrefixes)
                if (name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) return false;
            return true;
        }}

        private static void SyncSharpFuzz()
        {{
            try {{
                string[] candidates = {{ "SharpFuzz.Common", "SharpFuzz" }};
                foreach (var name in candidates) {{ try {{ Assembly.Load(name); }} catch {{ }} }}

                foreach (var a in AppDomain.CurrentDomain.GetAssemblies()) {{
                    string asmName = a.GetName().Name ?? a.FullName;
                    bool isApp = IsAppAssembly(asmName);
                    if (isApp) seenAppAssemblies.TryAdd(asmName, 1);

                    string[] types = {{ "SharpFuzz.Common.Trace", "SharpFuzz.Common.Instrumenter", "SharpFuzz.Trace", "SharpFuzz.Instrumenter" }};
                    foreach (var typeName in types) {{
                        Type t = a.GetType(typeName);
                        if (t == null) continue;

                        lastAttempt = $"Matched {{t.FullName}} in {{a.GetName().Name}}";

                        string[] members = {{ "SharedMem", "SharedMemory", "sharedMemory", "_sharedMemory" }};
                        foreach (var m in members) {{
                            var p = t.GetProperty(m, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                            if (p != null) {{
                                unsafe {{
                                    var boxedPtr = System.Reflection.Pointer.Box(globalShmAddr.ToPointer(), typeof(byte*));
                                    p.SetValue(null, boxedPtr);
                                }}
                                isSynced = true;
                                lastAttempt = $"Synced {{t.FullName}}.{{m}} (Property)";
                            }}

                            var f = t.GetField(m, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                            if (f != null) {{
                                f.SetValue(null, globalShmAddr);
                                isSynced = true;
                                lastAttempt = $"Synced {{t.FullName}}.{{m}} (Field)";
                            }}
                        }}
                    }}
                }}
                if (!isSynced) syncError = "SharpFuzz coverage type NOT found or members missing.";
                else syncError = "None";
            }} catch (Exception ex) {{ syncError = ex.Message; }}
        }}

        public static void AddCoverageEndpoints(this IEndpointRouteBuilder endpoints)
        {{
            endpoints.MapPost("/shm/create", () =>
            {{
                if (globalShmAddr == IntPtr.Zero) {{ Initialize(); }}
                else {{ SyncSharpFuzz(); }}
                return Results.Ok(new {{
                    mode = isFileBacked ? "file-backed-mmap" : "heap",
                    size = SHM_SIZE,
                    status = isSynced ? "synced" : "pending",
                    lastAttempt = lastAttempt,
                    error = syncError
                }});
            }});

            endpoints.MapPost("/shm/reset", () =>
            {{
                if (globalShmAddr != IntPtr.Zero)
                {{
                    lock (covLock)
                    {{
                        unsafe {{ byte* b = (byte*)globalShmAddr; for (int i = 0; i < SHM_SIZE; i++) b[i] = 0; }}
                        if (seenBuckets != null) Array.Clear(seenBuckets, 0, seenBuckets.Length);
                        totalClasses = 0;
                    }}
                    return Results.Ok("SHM Reset");
                }}
                return Results.Problem("SHM not initialized");
            }});

            endpoints.MapGet("/shm/coverage", () => {{
                // "edges" is the number of distinct (edge, hit-count-bucket) classes
                // discovered so far — the same bucketed novelty the per-request
                // X-Coverage-Delta header reports. "hits" remains the raw sum of the
                // live bitmap (recomputed here since this endpoint is polled rarely).
                var s = GetCoverageStats();
                return Results.Json(new {{ edges = totalClasses, hits = s.hits, size = SHM_SIZE }});
            }});

            endpoints.MapGet("/shm/health", () => {{
                // Reports facts only, not a verdict: SharpFuzz's Trace type lives in
                // SharpFuzz.Common.dll, never in the app's own rewritten assemblies, so
                // per-assembly "linked" status can't be measured by type reflection here.
                // The fail-closed ok/degraded decision is made engine-side (Go), which can
                // send real warm-up traffic and check whether the bitmap actually moves —
                // see void/go/coverage.go::checkCoverageHealth. app_assemblies below is
                // purely diagnostic context for that decision.
                bool shmBound = globalShmAddr != IntPtr.Zero;
                return Results.Json(new {{
                    shm_bound = shmBound,
                    mode = isFileBacked ? "file-backed-mmap" : "heap",
                    total_classes = totalClasses,
                    linked_assemblies = isSynced ? 1 : 0,
                    instrumented_types = InstrumentedTypeCount,
                    app_assemblies = seenAppAssemblies.Keys.ToArray()
                }});
            }});

            // Top-20+ #22: string/int literals harvested from the target's own IL at
            // instrument time (instrumentor/Program.cs::ConstantExtractor). Always 200
            // (possibly empty arrays) rather than 404-on-absence, since extraction is
            // unconditional -- an empty result just means the build found nothing to
            // harvest, not that this feature is unavailable.
            endpoints.MapGet("/shm/constants", () => {{
                return Results.Json(new {{ strings = ExtractedConstants.Strings, ints = ExtractedConstants.Ints }});
            }});

            endpoints.MapGet("/shm/coverage/traces", () => {{
                return Results.Json(new {{ traces = traceCoverage.Values.OrderByDescending(s => s.Timestamp) }});
            }});

            // Per-request trace lookup (reads and removes the snapshot — consumed once by the fuzzer).
            endpoints.MapGet("/shm/coverage/trace/{{requestId}}", (string requestId) => {{
                if (traceCoverage.TryGetValue(requestId, out var snap)) {{
                    traceCoverage.TryRemove(requestId, out _);
                    return Results.Json(snap);
                }}
                return Results.NotFound(new {{ error = "trace not found" }});
            }});
        }}

        public static (int edges, long hits) GetCoverageStats()
        {{
            if (globalShmAddr == IntPtr.Zero) return (0, 0);
            unsafe {{
                byte* b = (byte*)globalShmAddr;
                int edges = 0; long hits = 0;
                for (int i = 0; i < SHM_SIZE; i++) {{ if (b[i] > 0) {{ edges++; hits += b[i]; }} }}
                return (edges, hits);
            }}
        }}
    }}
}}
"""
    # Prefer Utilities/ (most ASP.NET projects use this convention); fall back to Helpers/.
    utilities_dir = output_path / main_proj.path / "Utilities"
    helpers_dir = output_path / main_proj.path / "Helpers"
    if utilities_dir.exists():
        target_dir = utilities_dir
    else:
        target_dir = helpers_dir
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / "CoverageExtensions.cs").write_text(code)
    print(f"  Generated Coverage Extensions in {main_proj.name}/{target_dir.name}/")

def _inject_into_startup_cs(startup_cs: Path, ns_prefix: str) -> bool:
    """Inject coverage middleware into Startup.cs (Bitwarden-pattern apps that use UseStartup<T>()).
    Returns True if injection was performed."""
    if not startup_cs.exists():
        return False

    content = startup_cs.read_text(encoding='utf-8-sig')

    # Only proceed if this is a real Startup class with Configure/ConfigureServices
    if 'public void Configure(' not in content and 'public void ConfigureServices(' not in content:
        return False

    modified = False

    # Inject UseCoverageMiddleware() after app.UseRouting()
    if 'UseCoverageMiddleware()' not in content:
        if 'app.UseRouting()' in content:
            content = content.replace(
                'app.UseRouting();',
                'app.UseRouting();\n\n        // UpsideFuzz: Coverage middleware\n        app.UseCoverageMiddleware();'
            )
            modified = True
        elif 'app.UseAuthentication()' in content:
            # Fallback: before UseAuthentication
            content = content.replace(
                'app.UseAuthentication();',
                '// UpsideFuzz: Coverage middleware\n        app.UseCoverageMiddleware();\n\n        app.UseAuthentication();'
            )
            modified = True

    # Inject AddCoverageEndpoints() inside UseEndpoints if present
    if 'AddCoverageEndpoints()' not in content:
        if 'endpoints.MapDefaultControllerRoute()' in content:
            content = content.replace(
                'endpoints.MapDefaultControllerRoute();',
                'endpoints.MapDefaultControllerRoute();\n\n            // UpsideFuzz: SHM coverage endpoints\n            endpoints.AddCoverageEndpoints();'
            )
            modified = True
        elif 'endpoints.MapControllers()' in content:
            content = content.replace(
                'endpoints.MapControllers();',
                'endpoints.MapControllers();\n\n            // UpsideFuzz: SHM coverage endpoints\n            endpoints.AddCoverageEndpoints();'
            )
            modified = True

    if modified:
        startup_cs.write_text(content, encoding='utf-8')
        print(f"  Injected SHM into Startup.cs")
    return modified


def inject_multi_shm_endpoints(result: MultiAnalysisResult, output_path: Path):
    """Inject SHM endpoints into the main project's Program.cs (or Startup.cs as fallback)."""
    main_proj = next((p for p in result.projects if p.name == result.main_project), result.projects[0])
    program_cs = output_path / main_proj.path / "Program.cs"
    startup_cs = output_path / main_proj.path / "Startup.cs"

    # Determine namespace prefix for the using directive
    ns_prefix = main_proj.root_namespace or result.main_project

    # First try Startup.cs (Bitwarden / legacy ASP.NET pattern)
    if startup_cs.exists():
        startup_content = startup_cs.read_text(encoding='utf-8-sig')
        if 'public void Configure(' in startup_content:
            _inject_into_startup_cs(startup_cs, ns_prefix)
            # Also patch Program.cs below for the using/Initialize call if needed

    if not program_cs.exists():
        return

    content = program_cs.read_text(encoding='utf-8-sig')
    # Match the subdir used by generate_multi_coverage_helper: Utilities/ if it exists, else Helpers/
    utilities_dir = output_path / main_proj.path / "Utilities"
    subdir_name = "Utilities" if utilities_dir.exists() else "Helpers"
    using_line = f"using {ns_prefix}.{subdir_name};"

    # Detect variable names dynamically
    builder_name = _detect_builder_name(content)
    app_name = _detect_app_name(content, builder_name)

    # Ensure using directive is present without altering nullable/pragma directives.
    if using_line not in content:
        lines = content.splitlines(keepends=True)
        insert_at = 0
        using_regex = re.compile(r'^\s*using\s+')
        for i, line in enumerate(lines):
            stripped = line.strip().lstrip('\ufeff')
            if not stripped:
                continue
            if stripped.startswith("//") or stripped.startswith("#"):
                insert_at = i + 1
                continue
            if using_regex.match(stripped):
                insert_at = i + 1
                continue
            break
        lines.insert(insert_at, using_line + "\n")
        content = "".join(lines)

    # Insert initialization call near builder creation (safe for file-scoped namespace).
    init_call = "CoverageExtensions.Initialize();"
    if init_call not in content:
        builder_stmt_re = re.compile(
            rf'(?m)^([ \t]*(?:var\s+)?{re.escape(builder_name)}\s*=\s*WebApplication\.CreateBuilder\(.*?\);\s*)$'
        )
        m = builder_stmt_re.search(content)
        if m:
            indent_match = re.match(r'^([ \t]*)', m.group(1))
            indent = indent_match.group(1) if indent_match else ""
            insert = f"{m.group(1)}\n{indent}{init_call}"
            content = content[:m.start()] + insert + content[m.end():]
        else:
            build_stmt_re = re.compile(
                rf'(?m)^([ \t]*(?:var\s+)?{re.escape(app_name)}\s*=\s*{re.escape(builder_name)}\.Build\(\);\s*)$'
            )
            m2 = build_stmt_re.search(content)
            if m2:
                indent_match = re.match(r'^([ \t]*)', m2.group(1))
                indent = indent_match.group(1) if indent_match else ""
                insert = f"{m2.group(1)}\n{indent}{init_call}"
                content = content[:m2.start()] + insert + content[m2.end():]

    # Only inject AddControllers if the project uses controller-based routing
    # Detect: has *Controller.cs files, or already references Controllers
    has_controllers = any(
        'Controller.cs' in f for p in result.projects for f in p.business_logic_files
    )

    if has_controllers and f"{builder_name}.Services.AddControllers()" not in content:
        if 'AddControllers' not in content:
            # Try to inject after a known service registration
            anchors = [
                rf'({re.escape(builder_name)}\.Services\.\w+\(.*?\);)',
                rf'(var\s+{re.escape(builder_name)}\s*=.*?;)',
            ]
            injected = False
            for anchor in anchors:
                m = re.search(anchor, content)
                if m:
                    content = content[:m.end()] + f"\n{builder_name}.Services.AddControllers();" + content[m.end():]
                    injected = True
                    break
            if not injected:
                content = content.replace(
                    f"var {builder_name} =",
                    f"var {builder_name} =",
                )

    # Middleware: inject UseCoverageMiddleware AFTER the exception-handler middleware is registered.
    # In ASP.NET Core, middleware registered first wraps everything inside it. If CoverageMiddleware
    # is registered BEFORE the exception handler (e.g. ConfigureRequestPipeline), then when a
    # controller throws an exception, the exception handler writes the 500 response first
    # (Response.HasStarted = true) before our finally block can inject X-Exception-Type headers.
    # By injecting AFTER ConfigureRequestPipeline / BEFORE MapControllers, our middleware sits
    # INSIDE the exception handler — so we see HasStarted=false and can set the header correctly.
    if "UseCoverageMiddleware()" not in content:
        injected = False
        # Preferred: inject after ConfigureRequestPipeline() call (nopCommerce, Umbraco, etc.)
        configure_pattern = rf'({re.escape(app_name)}\.ConfigureRequestPipeline\(\);)'
        m = re.search(configure_pattern, content)
        if m:
            content = content[:m.end()] + f"\n{app_name}.UseCoverageMiddleware();" + content[m.end():]
            injected = True
        # Fallback: inject before MapControllers() so we still wrap endpoint execution
        if not injected:
            map_controllers_pattern = rf'({re.escape(app_name)}\.MapControllers\(\);)'
            m = re.search(map_controllers_pattern, content)
            if m:
                content = content[:m.start()] + f"{app_name}.UseCoverageMiddleware();\n" + content[m.start():]
                injected = True
        # Last resort: inject immediately after Build()
        if not injected:
            build_pattern = rf'(var\s+{re.escape(app_name)}\s*=\s*{re.escape(builder_name)}\.Build\(\);)'
            m = re.search(build_pattern, content)
            if m:
                content = content[:m.end()] + f"\n{app_name}.UseCoverageMiddleware();" + content[m.end():]

    # Coverage Endpoints: inject before Run()/RunAsync()
    run_pattern = rf'(await\s+)?{re.escape(app_name)}\.(Run|RunAsync)\(\);'

    if has_controllers and "MapControllers()" not in content:
        content = re.sub(
            run_pattern,
            rf'{app_name}.MapControllers();\n\1{app_name}.\2();',
            content, count=1
        )

    if "AddCoverageEndpoints()" not in content:
        content = re.sub(
            run_pattern,
            rf'{app_name}.AddCoverageEndpoints();\n\1{app_name}.\2();',
            content, count=1
        )

    program_cs.write_text(content, encoding='utf-8')
    print(f"  Injected SHM into {main_proj.name}/Program.cs")


def generate_coverage_smoke_test(result: MultiAnalysisResult, output_path: Path):
    """Write verify_coverage.sh — a runtime check that instrumentation actually
    records edges. Run it AFTER the stand is up; it fails loudly if the coverage
    middleware/SHM is not active, catching the entire class of silently-broken
    coverage that a build-time script cannot see."""
    script = r"""#!/usr/bin/env bash
# AUTO-GENERATED by fuzz-prep-multi.py — coverage smoke test.
# Primary check is /shm/coverage (reliable). The per-response X-Coverage-* header is
# best-effort only and is often absent on fast endpoints (ASP.NET starts the response
# before our middleware's finally runs), so its absence does NOT mean coverage is broken.
# Usage: ./verify_coverage.sh [BASE_URL] [WARMUP_ENDPOINT]
set -euo pipefail

BASE="${1:-http://localhost:4000}"
WARM="${2:-/alive}"

echo "1) Ensuring SHM is synced ..."
curl -fsS -X POST "${BASE}/shm/create" >/dev/null 2>&1 || true

echo "2) Warming up ${BASE}${WARM} ..."
for i in 1 2 3; do
  curl -fsS -H "X-Fuzz-Request-Id: coverage-smoke-$(date +%s)-$i" "${BASE}${WARM}" >/dev/null 2>&1 || true
done

echo "3) Reading /shm/coverage ..."
COV="$(curl -fsS "${BASE}/shm/coverage" || true)"
echo "   ${COV:-<no response>}"

EDGES="$(printf '%s' "$COV" | grep -oE '"edges"[[:space:]]*:[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | head -1 || true)"

if [ -z "${EDGES:-}" ]; then
  echo "FAIL: /shm/coverage returned no edges count — SHM endpoints not wired or wrong image."
  exit 1
fi
if [ "${EDGES}" -le 0 ]; then
  echo "FAIL: edges=0 — instrumentation ran as a no-op (check build log for '[instrumentor] Done: instrumented=0')."
  exit 1
fi
echo "OK: coverage is active (edges=${EDGES}). Instrumentation verified."
"""
    dest = output_path / "verify_coverage.sh"
    dest.write_text(script, encoding="utf-8")
    try:
        dest.chmod(0o755)
    except Exception:
        pass
    print(f"  Wrote coverage smoke test: {dest.name} (run after the stand is up)")
